generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: launchpad.net
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 18 10:13:33 2026 GMT
  hsts: true
  hsts_max_age: 15552000
- host: api.launchpad.net
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 18 10:13:33 2026 GMT
  hsts: false
- host: ubuntu.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 30 04:13:35 2026 GMT
  hsts: true
  hsts_max_age: 15724800
domains:
- domain: launchpad.net
  dnssec: false
  caa:
  - 0 iodef "mailto:is-admin@canonical.com"
  - 0 issue "letsencrypt.org; accounturi=https://acme-v01.api.letsencrypt.org/acme/reg/32541290"
  - 0 issue "digicert.com"
  - 0 issue "letsencrypt.org"
  - 0 issuewild "letsencrypt.org"
  - 0 issuewild "digicert.com"
  spf: true
  dmarc: true
  dmarc_policy: none
- domain: ubuntu.com
  dnssec: false
  caa:
  - 0 issuewild "digicert.com"
  - 0 issue "digicert.com"
  - 0 issue "letsencrypt.org; accounturi=https://acme-v01.api.letsencrypt.org/acme/reg/32541290"
  - 0 issue "letsencrypt.org"
  - 0 issuewild "letsencrypt.org"
  - 0 iodef "mailto:is-admin@canonical.com"
  spf: true
  dmarc: true
  dmarc_policy: none
